version: 1
update_configs:
  - package_manager: "submodules"
    directory: "./"
    update_schedule: "daily"
    allowed_updates:
      - match:
          dependency_name: "final-1-vkutuev-test"
    ignored_updates:
      - match:
          dependency_name: "final-1-grading-tests"
